# Generated by Django 5.0.1 on 2024-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarot_rest", "0005_reading"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
