# Generated by Django 5.0.1 on 2024-06-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarot_rest", "0006_reading_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="reading",
            name="cards",
            field=models.TextField(blank=True, null=True),
        ),
    ]
