# Generated by Django 5.0.1 on 2024-06-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarot_rest", "0007_reading_cards"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reading",
            name="cards",
        ),
        migrations.AddField(
            model_name="reading",
            name="cards",
            field=models.ManyToManyField(to="tarot_rest.card"),
        ),
    ]
