# Generated by Django 5.0.1 on 2024-07-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarot_rest", "0008_remove_reading_cards_reading_cards"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="img_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
